// Package reporter generates scan reports in JSON, HTML, and Markdown formats.
package reporter

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/venom-scanner/venom/internal/storage"
)

// Reporter generates formatted output from the scan database.
type Reporter struct {
	db     *storage.DB
	scanID string
}

// NewReporter creates a Reporter for a specific scan.
func NewReporter(db *storage.DB, scanID string) *Reporter {
	return &Reporter{db: db, scanID: scanID}
}

// Generate produces a report in the specified format and writes it to a file
// (or stdout if path is empty).
func (r *Reporter) Generate(ctx context.Context, format, outputPath string) error {
	var content []byte
	var err error

	switch strings.ToLower(format) {
	case "json":
		content, err = r.generateJSON(ctx)
	case "html":
		content, err = r.generateHTML(ctx)
	case "md", "markdown":
		content, err = r.generateMarkdown(ctx)
	default:
		return fmt.Errorf("unsupported format: %s", format)
	}

	if err != nil {
		return err
	}

	if outputPath == "" {
		_, err = os.Stdout.Write(content)
		return err
	}

	return os.WriteFile(outputPath, content, 0644)
}

// generateJSON produces a JSON report.
func (r *Reporter) generateJSON(ctx context.Context) ([]byte, error) {
	return r.db.ExportFindingsJSON(ctx, r.scanID)
}

// generateMarkdown produces a Markdown report.
func (r *Reporter) generateMarkdown(ctx context.Context) ([]byte, error) {
	summary, err := r.db.GetScanSummary(ctx, r.scanID)
	if err != nil {
		return nil, err
	}
	findings, err := r.db.GetFindings(ctx, r.scanID)
	if err != nil {
		return nil, err
	}

	var b strings.Builder

	b.WriteString("# ⚡ Scann3r Report\n\n")
	b.WriteString(fmt.Sprintf("**Target:** %s  \n", summary["target"]))
	b.WriteString(fmt.Sprintf("**Scan ID:** `%s`  \n", r.scanID))
	b.WriteString(fmt.Sprintf("**Date:** %s  \n", time.Now().Format("2006-01-02 15:04:05")))
	b.WriteString(fmt.Sprintf("**Status:** %s  \n\n", summary["status"]))

	b.WriteString("## Summary\n\n")
	b.WriteString("| Metric | Value |\n|---|---|\n")
	b.WriteString(fmt.Sprintf("| URLs Discovered | %v |\n", summary["urls_found"]))
	b.WriteString(fmt.Sprintf("| JS Files Analyzed | %v |\n", summary["js_files_found"]))
	b.WriteString(fmt.Sprintf("| Forms Found | %v |\n", summary["forms_found"]))
	b.WriteString(fmt.Sprintf("| Parameters Tested | %v |\n", summary["params_found"]))
	b.WriteString(fmt.Sprintf("| Requests Sent | %v |\n", summary["requests_sent"]))
	b.WriteString(fmt.Sprintf("| WAF Blocks | %v |\n", summary["waf_blocks"]))
	b.WriteString(fmt.Sprintf("| Errors | %v |\n\n", summary["errors"]))

	// Findings by severity
	if sevMap, ok := summary["findings"].(map[string]int64); ok {
		b.WriteString("## Findings by Severity\n\n")
		b.WriteString("| Severity | Count |\n|---|---|\n")
		for _, sev := range []string{"critical", "high", "medium", "low", "info"} {
			if count, ok := sevMap[sev]; ok && count > 0 {
				icon := severityIcon(sev)
				b.WriteString(fmt.Sprintf("| %s %s | %d |\n", icon, titleCase(sev), count))
			}
		}
		b.WriteString("\n")
	}

	// Detailed findings
	if len(findings) > 0 {
		b.WriteString("## Detailed Findings\n\n")
		for i, f := range findings {
			icon := severityIcon(f.Severity)
			b.WriteString(fmt.Sprintf("### %d. %s [%s] %s in `%s`\n\n",
				i+1, icon, strings.ToUpper(f.Severity), strings.ToUpper(f.Type), f.Parameter))
			b.WriteString(fmt.Sprintf("- **URL:** `%s`\n", f.URL))
			b.WriteString(fmt.Sprintf("- **Method:** %s\n", f.Method))
			b.WriteString(fmt.Sprintf("- **Parameter:** `%s` (%s)\n", f.Parameter, f.ParameterLocation))
			b.WriteString(fmt.Sprintf("- **Payload:** `%s`\n", f.Payload))
			if f.MutationStrategy != "" && f.MutationStrategy != "original" {
				b.WriteString(fmt.Sprintf("- **WAF Bypass:** %s\n", f.MutationStrategy))
			}
			b.WriteString(fmt.Sprintf("- **Confidence:** %.0f%%\n", f.Confidence*100))
			b.WriteString(fmt.Sprintf("- **Evidence:**\n```\n%s\n```\n\n", f.Evidence))
			b.WriteString("---\n\n")
		}
	}

	b.WriteString("\n*Generated by Scann3r v1.0.0*\n")

	return []byte(b.String()), nil
}

// generateHTML produces a standalone HTML report.
func (r *Reporter) generateHTML(ctx context.Context) ([]byte, error) {
	summary, err := r.db.GetScanSummary(ctx, r.scanID)
	if err != nil {
		return nil, err
	}
	findings, err := r.db.GetFindings(ctx, r.scanID)
	if err != nil {
		return nil, err
	}

	summaryJSON, _ := json.Marshal(summary)
	findingsJSON, _ := json.Marshal(findings)

	html := buildHTMLReport(string(summaryJSON), string(findingsJSON), r.scanID)
	return []byte(html), nil
}

func severityIcon(sev string) string {
	switch sev {
	case "critical":
		return "🔴"
	case "high":
		return "🟠"
	case "medium":
		return "🟡"
	case "low":
		return "🔵"
	case "info":
		return "⚪"
	default:
		return "⚪"
	}
}

// titleCase capitalises the first letter of a string.
func titleCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}

// buildHTMLReport creates a self‑contained HTML report with embedded CSS & JS.
func buildHTMLReport(summaryJSON, findingsJSON, scanID string) string {
	return fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Scann3r Report — %s</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',system-ui,-apple-system,sans-serif;background:#0a0a0f;color:#e0e0e0;line-height:1.6}
.container{max-width:1200px;margin:0 auto;padding:2rem}
header{text-align:center;padding:3rem 0 2rem;border-bottom:1px solid #1a1a2e}
header h1{font-size:2.5rem;background:linear-gradient(135deg,#00ff87,#60efff);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:.5rem}
header p{color:#888;font-size:1.1rem}
.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem;margin:2rem 0}
.stat{background:linear-gradient(135deg,#1a1a2e,#16213e);border:1px solid #1f2937;border-radius:12px;padding:1.5rem;text-align:center}
.stat .value{font-size:2rem;font-weight:700;color:#60efff}
.stat .label{font-size:.85rem;color:#888;text-transform:uppercase;letter-spacing:.5px}
.severity-bar{display:flex;gap:.5rem;margin:2rem 0;flex-wrap:wrap}
.sev-badge{padding:.5rem 1.25rem;border-radius:20px;font-weight:600;font-size:.9rem}
.sev-critical{background:#ff004420;color:#ff0044;border:1px solid #ff004440}
.sev-high{background:#ff660020;color:#ff8800;border:1px solid #ff660040}
.sev-medium{background:#ffcc0020;color:#ffcc00;border:1px solid #ffcc0040}
.sev-low{background:#0088ff20;color:#0088ff;border:1px solid #0088ff40}
h2{font-size:1.5rem;color:#60efff;margin:2rem 0 1rem;padding-bottom:.5rem;border-bottom:1px solid #1a1a2e}
.finding{background:#111;border:1px solid #1f2937;border-radius:12px;padding:1.5rem;margin-bottom:1rem;transition:border-color .2s}
.finding:hover{border-color:#60efff40}
.finding-header{display:flex;align-items:center;gap:.75rem;margin-bottom:1rem}
.finding-type{font-weight:700;text-transform:uppercase;font-size:1.1rem}
.finding-details{display:grid;grid-template-columns:120px 1fr;gap:.3rem .75rem;font-size:.9rem}
.finding-details dt{color:#888}
.finding-details dd{color:#ccc;word-break:break-all}
.evidence{background:#0a0a0f;border:1px solid #1f2937;border-radius:8px;padding:1rem;margin-top:1rem;font-family:'Cascadia Code','Fira Code',monospace;font-size:.85rem;overflow-x:auto;color:#aaa;white-space:pre-wrap}
footer{text-align:center;padding:2rem;color:#555;font-size:.85rem}
</style>
</head>
<body>
<div class="container">
<header>
<h1>⚡ Scann3r Report</h1>
<p>Scan ID: %s</p>
</header>
<div id="content"></div>
<footer>Generated by Scann3r v1.0.0</footer>
</div>
<script>
const summary = %s;
const findings = %s;
const content = document.getElementById('content');

// Stats cards
const statsHTML = '<div class="stats">' +
['urls_found:URLs Found','js_files_found:JS Files','forms_found:Forms','params_found:Parameters',
 'requests_sent:Requests','waf_blocks:WAF Blocks','errors:Errors']
.map(s => {
  const [k,l] = s.split(':');
  return '<div class="stat"><div class="value">'+(summary[k]||0)+'</div><div class="label">'+l+'</div></div>';
}).join('') + '</div>';

// Severity badges
const sevs = summary.findings || {};
const sevHTML = '<div class="severity-bar">' +
['critical','high','medium','low'].filter(s=>sevs[s]).map(s =>
  '<span class="sev-badge sev-'+s+'">'+(s.charAt(0).toUpperCase()+s.slice(1))+': '+sevs[s]+'</span>'
).join('') + '</div>';

// Findings
let findingsHTML = '<h2>Findings ('+findings.length+')</h2>';
findings.forEach((f,i) => {
  findingsHTML += '<div class="finding"><div class="finding-header">' +
    '<span class="sev-badge sev-'+f.Severity+'">'+(f.Severity||'').toUpperCase()+'</span>' +
    '<span class="finding-type">'+f.Type+'</span></div>' +
    '<dl class="finding-details">' +
    '<dt>URL</dt><dd>'+f.URL+'</dd>' +
    '<dt>Parameter</dt><dd>'+f.Parameter+' ('+f.ParameterLocation+')</dd>' +
    '<dt>Payload</dt><dd>'+escapeHtml(f.Payload)+'</dd>' +
    (f.MutationStrategy && f.MutationStrategy!=='original' ? '<dt>WAF Bypass</dt><dd>'+f.MutationStrategy+'</dd>' : '') +
    '<dt>Confidence</dt><dd>'+Math.round(f.Confidence*100)+'%%</dd>' +
    '</dl>' +
    '<div class="evidence">'+escapeHtml(f.Evidence)+'</div></div>';
});

content.innerHTML = statsHTML + sevHTML + findingsHTML;

function escapeHtml(s){if(!s)return'';return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
</script>
</body>
</html>`, scanID, scanID, summaryJSON, findingsJSON)
}
